#pragma once
#ifndef RF_FASTFLOW_CONFIG_HXX
#define RF_FASTFLOW_CONFIG_HXX

#define FOR_CHUNK_SIZE 10
#define FOR_NUM_WORKERS 8
#define FOR_SPINWAIT true
#define FOR_SPINBARRIER true
#define FF_SAMPLES_PER_TREE {400, 500}
#define FF_TREE_COUNTS {10, 50, 100, 150, 200}
#define FARM_NUM_WORKERS 2

#endif
