#pragma once
#ifndef RF_FASTFLOW_CONFIG_HXX
#define RF_FASTFLOW_CONFIG_HXX

#define FOR_CHUNK_SIZE 1
#define FOR_NUM_WORKERS 6
#define FOR_SPINWAIT false
#define FOR_SPINBARRIER false
#define FF_SAMPLES_PER_TREE {400}
#define FF_TREE_COUNTS {10, 50, 100, 150, 200}
#define FARM_NUM_WORKERS 2
#define MAP_SPINWAIT false
#define MAP_SPINBARRIER false
#define CACHE_OPTIMIZATION true
#define MAP_NUM_WORKERS 4
#define COMPLEXITY_THRESHOLD_FARM 50000
#define FF_SAMPLES_PER_TREE_TEST {100}
#define USE_PARALLEL_MAP true
#define EN_NUM_WORKERS 1
#define WN_FIRST_NUM_WORKERS 2
#define WN_SECOND_NUM_WORKERS 1
#endif
